### ISSUE TITLE
Coverage is not computed

### ISSUE THREAD

**Issue by JulienPeloton** [astrolabsoftware/fink-client#15]
**Describe the issue**
In the CI, the tests are launched from the `tests` directory, but the coverage analysis takes place in the root directory of the project - hence `sonar` reports empty coverage... 

Action item: two possibilities here
1) launching tests from the root directory (updating paths for test scripts).
2) launching sonar analysis from the test repository. In this case, one would have to pass `sonar` properties directly inside travis script instead of reading the sonar-project.properties file.

**Comment by JulienPeloton** [comment]
Note: I have produced a quick and dirty fix in the master branch (https://github.com/astrolabsoftware/fink-client/commit/fbbdbd67d3756c850f42d16a613d8b40bf952b95) to fix the failing build.

**Comment by JulienPeloton** [comment]
Third possiblity (and the one to take): update `.coveragerc` and `sonar-project.properties` with correct path to `.coverage`... :-)

**Comment by cAbhi15** [comment]
> Note: I have produced a quick and dirty fix in the master branch ([fbbdbd6](https://github.com/astrolabsoftware/fink-client/commit/fbbdbd67d3756c850f42d16a613d8b40bf952b95)) to fix the failing build.

Does it fix the failing build?

**Comment by cAbhi15** [comment]
> Third possiblity (and the one to take): update `.coveragerc` and `sonar-project.properties` with correct path to `.coverage`... :-)

Is the third possibility the best way to proceed?

**Comment by JulienPeloton** [comment]
> Does it fix the failing build?

No the build is fixed (travis), but sonar still complained because it could not find the coverage report (not generated - and it would have looked in the wrong folder anyway as the coverage would have been generated in `test`).

> Is the third possibility the best way to proceed?

It seems to me - at least the easiest one. I am trying it now :-)

**Comment by JulienPeloton** [comment]
Now the sonar script runs correctly, but coverage is not computed on Travis... 

```
## On my laptop
Name                      Stmts   Miss  Cover
---------------------------------------------
fink_client/__init__.py       1      0   100%
fink_client/consumer.py      79     30    62%
tests/testConsumer.py        20      0   100%
tests/testProducer.py        41      1    98%
---------------------------------------------
TOTAL                       141     31    78%

## On Travis
Coverage.py warning: No data was collected. (no-data-collected)

Name    Stmts   Miss  Cover

---------------------------
No data to report.
The command "./tests/integration_test.sh" exited with 1.
```

I tested option 1 & 3, and both gives the same (empty) result...

**Comment by cAbhi15** [comment]
Thanks @JulienPeloton 
I will take care of this along with the issue #16

**Comment by JulienPeloton** [comment]
Thanks @cAbhi15, I have a branch opened (https://github.com/astrolabsoftware/fink-client/tree/issues/15/coverage) in case you want to see what has been implemented so far (but this is not working on travis as mentioned above...).

**Comment by JulienPeloton** [comment]
Fixed in https://github.com/astrolabsoftware/fink-client/commit/bce41012af3e41c4cab48f33d550d3f958b7b16c
