### ISSUE TITLE
Bug fix return_offsets fink_client.consumer

### ISSUE THREAD

**Issue by Oumar1777** [astrolabsoftware/fink-client#178]
**Describe the issue**
I found an error using fink_datatransfer
In print_offsets which calls return_offsets of consumer.py, the function "return_offsets" only returns the offset and the lag of the last partition instead of returning the sum

**System Information:**
_Please update accordingly_
 - Operating System: [Debian]:
 - Fink client version: [`0.0.1`]
 - Occurred on which branch and with what commit: [`master-fab987b`]

**Additional context**

**Comment by JulienPeloton** [comment]
Fixed in #179
