### ISSUE TITLE
Multiprocessing datatransfer

### ISSUE THREAD

**Issue by Oumar1777** [astrolabsoftware/fink-client#180]
**Describe the issue**
Use multiprocessing to speed up the download of alerts by a Fink client. 
Each process handles a different partition of the topic, significantly reducing the download time.

**Additional context**
Functional version of Datatransfer with multiprocessing for Fink Client
Note: The processes are losing too much time waiting for alerts to load in different partitions.
Possible optimization: Switch to another partition when the downloaded data does not reach the fixed batch size.
Potential risk: Increased time due to frequent partition changes.
To do: Find the ideal max timeout and batch size for better optimization.

**Comment by JulienPeloton** [comment]
Fixed in #181
