### ISSUE TITLE
propagate changes made in fink-broker (distribute all alert data)

### ISSUE THREAD

**Issue by cAbhi15** [astrolabsoftware/fink-client#19]
**Describe the issue**
Currently the sample alerts consists of only a few columns of the original alert data.

On the fink-broker side filters are applied to remove unimportant alerts. The changes made in [PR 269](https://github.com/astrolabsoftware/fink-broker/pull/269) distributes the whole alert data (original + added value by fink-broker). 

Propagate these changes to `fink-client` by adding sample alert files containing complete data and relevant schema file.

**Comment by JulienPeloton** [comment]
Fix in #20. Thanks @cAbhi15
