### ISSUE TITLE
Updating gitignore file

### ISSUE THREAD

**Issue by tallamjr** [astrolabsoftware/fink-client#21]
**Describe the issue**
When attempting to run `bin/fink_client_test.sh` for the first time one needs to ensure that `$FINK_CLIENT_HOME` is set beforehand, so it would be useful if this was put as an instruction in the `README` perhaps.

When this is set however and one runs `bin/fink_client_test.sh`, there are several files that are created and not track; some of these include:
```
        .coverage
        fink_client.egg-info/
        notebooks/.ipynb_checkpoints/
        schemas/distribution_schema.avsc
```
It might be good to update the `.gitignore` to not track some these

**System Information:**
 - Operating System: [`macOS-10.14.16`]:
 - Fink client version: [`0.0.1`]
 - Occurred on which branch and with what commit: [`master-9f7f464`]

**Comment by JulienPeloton** [comment]
Fix in #22
