### ISSUE TITLE
Uncaught conditional in CI tests of a forked repo

### ISSUE THREAD

**Issue by tallamjr** [astrolabsoftware/fink-client#23]
**Describe the issue**

A forked build failed with this error:

        ERROR: Error during SonarQube Scanner execution
        ERROR: Not authorized. Please check the properties sonar.login and sonar.password.

        The command "if [ $TRAVIS_PULL_REQUEST == false ] || [ $TRAVIS_PULL_REQUEST_SLUG == "astrolabsoftware/fink-client"]; then coverage xml -i; sonar-scanner; fi" exited with 1.

The conditional should have caught that the tests was not a
`TRAVIS_PULL_REQUEST` or the `TRAVIS_PULL_REQUEST_SLUG` was not
`astrolabsoftware/fink_client` but was a fork repo instead

By setting the logic to 'true' then sonar should only run when it is
a PR or when it is _not_ a forked repo.

REF:
https://travis-ci.com/tallamjr/fink-client/jobs/238010364 <-- Failing
https://travis-ci.com/tallamjr/fink-client/jobs/238066578 <-- Passing

**System Information:**
 - Operating System: [`macOS-10.14.16`]:
 - Fink client version: [`0.0.1`]
 - Occurred on which branch and with what commit: [`master-9f7f464`]

**Additional context**
This would potentially require the same change in [fink-broker](https://github.com/astrolabsoftware/fink-broker) too perhaps.

**Comment by JulienPeloton** [comment]
Fix in #24. Thanks @tallamjr
